/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/domac/crddemo/pkg/apis/crddemo/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MydemoLister helps list Mydemos.
type MydemoLister interface {
	// List lists all Mydemos in the indexer.
	List(selector labels.Selector) (ret []*v1.Mydemo, err error)
	// Mydemos returns an object that can list and get Mydemos.
	Mydemos(namespace string) MydemoNamespaceLister
	MydemoListerExpansion
}

// mydemoLister implements the MydemoLister interface.
type mydemoLister struct {
	indexer cache.Indexer
}

// NewMydemoLister returns a new MydemoLister.
func NewMydemoLister(indexer cache.Indexer) MydemoLister {
	return &mydemoLister{indexer: indexer}
}

// List lists all Mydemos in the indexer.
func (s *mydemoLister) List(selector labels.Selector) (ret []*v1.Mydemo, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Mydemo))
	})
	return ret, err
}

// Mydemos returns an object that can list and get Mydemos.
func (s *mydemoLister) Mydemos(namespace string) MydemoNamespaceLister {
	return mydemoNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MydemoNamespaceLister helps list and get Mydemos.
type MydemoNamespaceLister interface {
	// List lists all Mydemos in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.Mydemo, err error)
	// Get retrieves the Mydemo from the indexer for a given namespace and name.
	Get(name string) (*v1.Mydemo, error)
	MydemoNamespaceListerExpansion
}

// mydemoNamespaceLister implements the MydemoNamespaceLister
// interface.
type mydemoNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Mydemos in the indexer for a given namespace.
func (s mydemoNamespaceLister) List(selector labels.Selector) (ret []*v1.Mydemo, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Mydemo))
	})
	return ret, err
}

// Get retrieves the Mydemo from the indexer for a given namespace and name.
func (s mydemoNamespaceLister) Get(name string) (*v1.Mydemo, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("mydemo"), name)
	}
	return obj.(*v1.Mydemo), nil
}
